# Theme settings
jg:
    baseurl:
    title: Jonnathan Griffin
    theme_color: '#0976f8' # Define theme primary color with HEX value
    language: en-US # Use ISO language and country codes to setup language of your website - https://www.w3schools.com/tags/ref_language_codes.asp and https://www.w3schools.com/tags/ref_country_codes.asp
    header:
        logo:
            text: Jonnathan Griffin
            image:
        nav:
            - item_name: Favorite Links
              item_url: /links
        cta:
            label: posts
            url: /posts
            icon: lock # Choose from 266 icons in "Feather" icon set, list of all icons is available here - https://feathericons.com
    footer:
        logo:
            text: Jonnathan Griffin
            image:
        text: griffin (dot) jonnathan (@) gmail.com
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your Disqus forum shortname to activate comments site-wide

# Defining collections
collections:
    post:
        output: true

# Defining defaults
defaults:
    -
        scope:
            path: ''
            type: 'post'
        values:
            layout: 'post-single'

# SASS settings
sass:
    sass_dir: ./theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./theme/_layouts
includes_dir: ./theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
